### ISSUE TITLE
[5pt]Android 6.0 (marshmallow level 23)に対応している

### ISSUE THREAD

**Issue by tyanio** [enpitut2019/ShoppingReminder#25]
# 調査
どうやって実装できそうか調べる…
下参照！
***
# 調査結果
- PlacesAPIは関係なさそう？ForegroundService関連を直すと動くかもしれない
- SDK 23に対応したLocationServiceクラスを新しく作ってみる？

---
# ゴール！
ForegroundServiceを使っているクラスをAPI23に対応させる
API23・24で既存の機能が使えたらOK！

**Comment by playingmiss** [comment]
### android 8.0 からバックグラウンドサービス使用に制限がかかる
https://qiita.com/gksdyd88/items/30df1f220001fad69d9e

SDKによって処理を変える必要がありそう

**Comment by tyanio** [comment]
# PlacesAPIに関して
今のところPlacesAPIがAndroidのVerを指定している記述は確認できない
MinSDKを下げてエラーが出るのは基本的にはForeGroundService関連のエラー
APIという概念から考えてもAndroid側のVerを指定することはあんまりないんじゃない？
***
MinSDKを23(Ver6.0)に下げてPlacesAPIに通しても静的なエラーは確認できず！
動かすためにいろいろコメントアウトしてるから結局正常動作は確認できていないけど、ForeGroundServiceを変えたら何とかなる期待はあるかな

**Comment by playingmiss** [comment]
# android 8.0 で変更されたforeground実行の変更点
https://rakuishi.com/archives/android-oreo-notification-foreground/

- compileSdkVersion, targetSdkVersionをSDK 26で設定すると通知とforeground実行に制限
 - 通知毎にチャンネルを紐づける
 - 以前のバージョンではバックグラウンドサービス作成→Service.startForegroundService()メソッドでフォアグラウンド実行できた
   - Oreoではそれに加え5秒以内に Service.startForeground()メソッドを使用しないとクラッシュする

明らかにSDK26を境に処理内容が異なるのでクラスを分けたほうが明快かも
