### ISSUE TITLE
GPSを使える

### ISSUE THREAD

**Issue by Yamakatsu63** [enpitut2019/ShoppingReminder#3]
地図とは書いたのですが地図自体はこのアプリでは使うつもりがないのでそのつもりで！

**Comment by tyanio** [comment]
-  https://docs.unity3d.com/jp/460/ScriptReference/LocationService.Start.html

- http://blog.be-style.jpn.com/article/54157817.html

**Comment by playingmiss** [comment]
- http://kan-kikuchi.hatenablog.com/entry/OnApplicationPause
アプリを終了、もしくは一時停止した時の動作を呼び出すメソッド

**Comment by NishidaYujiro** [comment]
Service開始時にGPSをoffにしているとアプリが落ちる
---
解決しました

**Comment by NishidaYujiro** [comment]
# ~GPSをONにしていないのに、GPS作動中となる~
GPSがoffの状態で、アプリに位置情報使用の許可を与えると、GPSがonになっていないのに、フォアグランドサービスが起動する。
# 解決しました！
