### ISSUE TITLE
通知を受け取ることができる

### ISSUE THREAD

**Issue by tyanio** [enpitut2019/ShoppingReminder#4]
- [x] 開発側で仮に決めた場所に近づくと通知が行くようにする

**Comment by Yamakatsu63** [comment]
# 参考サイト
- http://baba-s.hatenablog.com/entry/2018/12/18/085000

**Comment by Yamakatsu63** [comment]
# アイコンについて
参考サイト
Androidで通知アイコンが白くなる件の対処法、以降を参照
https://develop.hateblo.jp/entry/unity-android-push-icon

**Comment by Yamakatsu63** [comment]
# アイコン設定スクリプトの参考サイト
http://baba-s.hatenablog.com/entry/2018/12/18/085000

- ChannelName -> アプリ内の通知設定のときにユーザに表示される
- Description -> アプリ内の通知設定のときにChannelNameの下に表示される
- Title -> 通知バーのタイトルに表示される
- Text -> 通知バーのコンテンツに表示される

**Comment by Yamakatsu63** [comment]
# ビルドの際のSDKVersionエラーの解決法
https://teratail.com/questions/169689

**Comment by Yamakatsu63** [comment]
# AndroidStudioへアイコンをインポートする方法

プロジェクトの[res]を右クリック->[New]->[Image Asset]を選択して，画像があるパスを指定すると一枚の画像から複数のサイズのアイコンを作ってくれる

作成されたアイコンは[res]->[drawable]内に追加される
