### ISSUE TITLE
閉じても通知が受け取れる

### ISSUE THREAD

**Issue by tyanio** [enpitut2019/ShoppingReminder#5]
バックグラウンドでも通知が受け取れるようにするのがDone

**Comment by playingmiss** [comment]
- バックグラウンド状態の判別(Run in Background)
https://freelyapps.net/behavior-of-onapplication/

**Comment by Yamakatsu63** [comment]
位置情報の取得と通知をバックグラウンドで実装しなければいけないので，Serviceクラスを継承したクラスでどちらとも実装．
Serviceの開始・終了やUI関連等の動きをActivityクラスを継承したクラスで実装.
