### ISSUE TITLE
UI関連

### ISSUE THREAD

**Issue by tyanio** [enpitut2019/ShoppingReminder#6]

**Comment by tyanio** [comment]
# DesignEditor等
https://developer.android.com/studio/write/layout-editor?hl=JA
https://developer.android.com/guide/topics/ui/declaring-layout.html?hl=JA#java
https://developer.android.com/training/constraint-layout/index.html?hl=JA

**Comment by tyanio** [comment]
# Translation等
https://developer.android.com/studio/write/translations-editor?hl=JA

**Comment by NishidaYujiro** [comment]
# バグ確認しました
- マルチタスクボタンを2度押すとアプリが落ちる。
- アプリを落とすとデータベースを初期化してしまう。

**Comment by Yamakatsu63** [comment]
# マルチタスクボタンを複数回押すと強制終了するバグ
MainActivityのRecieverが原因だったようで、現在使ってなかったので消したらバグがなくなりました

# アプリを落とすとデータベースが初期化されるバグ
MainActivityのonCreate()の中の
```
requisiteDBBuilder.onUpgrade(db,0,0);
```
をけしたら解決しました
