### ISSUE TITLE
買いたい商品のカテゴリを選べる

### ISSUE THREAD

**Issue by tyanio** [enpitut2019/ShoppingReminder#7]
# ゴール
買いたいもののカテゴリをプルダウン形式のセレクトボックスで指定できる

**Comment by Yamakatsu63** [comment]
買いたい物のカテゴリをセレクトボックスで指定してもらう

**Comment by Yamakatsu63** [comment]
プルダウンをSpinnerクラスで作成する

**Comment by playingmiss** [comment]
- Spinnerを用いたセレクトボックスの作成方法
https://techacademy.jp/magazine/3705

**Comment by playingmiss** [comment]
- セレクトボックスのアイテムを取得する
https://www.ipentec.com/document/android-spinner-get-selected-item

**Comment by playingmiss** [comment]
- (多分一番わかりにくい)Spinnerに表示する値と内部の値の変え方
https://yan-note.blogspot.com/2012/10/android-spinner.html

**Comment by tyanio** [comment]
http://androidguide.nomaki.jp/html/widget/spinner/getitem.html
